name: 'Slack Action Status'
description: 'Github action to notify Slack using a message template'
author: 'navilan'
branding: 
  icon: bell
  color: yellow 
inputs:
  githubToken: 
    required: true
    description: "Use secrets.GITHUB_TOKEN" 
  botToken: 
    required: true
    description: Slack APP Bot Token
  channelId: 
    required: true
    description: Slack Channel ID
  status: 
    required: true
    description: Status of the build as of now
  params:
    required: false
    description: "Additional parameters as string in '- <key>: <value>' format"
  indicators:
    required: false
    description: "Status indicators as string in '- <key>: <value>' format"
  messageId: 
    required: false
    description: Slack Message ID for updates
  sourceSHA: 
    required: false
    description: Override for the commit sha to be used as the source of the event
  templateFile: 
    required: false
    description: Message template using Slack Blocks Kit
  inclusionSuffix: 
    required: false
    description: Suffix that marks a step to be included in the message
  forceSuccess:
    required: false
    description: Forces the current job status to be success overriding the API
  forceFailure:
    required: false
    description: Forces the current job status to be failed overriding the API
runs:
  using: 'node12'
  main: 'dist/index.js'
