name: 'Slack Action Status'
description: 'Github Action to Notify Slack using a message template'
author: 'navilan'
branding: 
  icon: bell
  color: yellow 
inputs:
  githubToken: 
    required: true
    description: "Use secrets.GITHUB_TOKEN" 
  botToken: 
    required: true
    description: Slack APP Bot Token
  channelId: 
    required: true
    description: Slack Channel ID
  messageId: 
    required: false
    description: Slack Message ID for updates
  templateFile: 
    required: false
    description: Message template using the Slack Blocks Spec
  status: 
    required: true
    description: Status of the build as of now
  indicators:
    required: false
    description: "Status indicators as string in '- <key>: <value>' format"
  params:
    required: false
    description: "Additional parameters as string in '- <key>: <value>' format"
  excludeStepSuffix: 
    required: false
    description: Suffix that marks a step to be excluded
runs:
  using: 'node12'
  main: 'dist/index.js'
